### ISSUE TITLE
require('spm-webpack')

### ISSUE THREAD

**Issue by Superman-wc** [spmjs/spm-webpack#18]
spm-webpack/node_modules/spm-client/lib/install.js:43

function\* install(args, config) {
        ^
SyntaxError: Unexpected token *

我只是想使用一下SPM里的模块， 所以我只用了SPMWebpackPlugin 这个

**Comment by popomore** [comment]
请使用 iojs 或加 --harmony

**Comment by sorrycc** [comment]
试试在 require spm-webpack 之前先 `require('gnode')`
