### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm-webpack#2]
**特性**
- `按需加载` -- [example](https://github.com/spmjs/examples/tree/spm-webpack/load-on-demand)
  
  ![](https://t.alipayobjects.com/images/T11KNfXhloXXXXXXXX.png)
- `global` -- 使用页面上已有的 window.jQuery、window.React 等, [example](https://github.com/spmjs/examples/tree/spm-webpack/react)
- `提取公用文件` -- [example](https://github.com/spmjs/examples/tree/spm-webpack/common-file)
  
  ![](https://t.alipayobjects.com/images/T1NvdfXe4lXXXXXXXX.png)
- `提取公用库` -- [example](https://github.com/spmjs/examples/tree/spm-webpack/common-pkg)
- `js require css`
- `提取 css` -- [example](https://github.com/spmjs/examples/tree/spm-webpack/less)
  
  ![](https://t.alipayobjects.com/images/T1e2FfXfxcXXXXXXXX.png)
- `提取图片和字体文件`
- `复制 html 和图片文件`
- `自定义 prebuild, build, postbuild 脚本`
- `循环依赖` -- [example](https://nodejs.org/api/modules.html#modules_cycles)

**语言扩展**
- `less` -- [example](https://github.com/spmjs/examples/tree/spm-webpack/less)
- `jsx`
- `coffee`
- `es6` -- 通过 babel 实现
- `handlebars`
- `tpl 和 html 模板`
- `anima-template`
- `autoprefixer`

**输出格式**
- `umd`
- `debug file`

**输出路径**
- `hash`
- `name 和 version`

**体验改进**
- `package.json 非必选`
- `构建前安装依赖`
- `构建前清空目标文件夹`
- `不输出日志(静默模式)`
- `启动和执行时间都快了` -- 一个真实的项目例子，从 60s+ 到 20s，且 80% 的时间消耗都在压缩上
  
  ![](https://t.alipayobjects.com/images/T1mK4fXjXnXXXXXXXX.gif)
- `修复 server 和 build 执行顺序不一致的问题`

**即将支持**
- `sprites`
- `worker`

**Comment by afc163** [comment]
example 赞

**Comment by popomore** [comment]
好像很厉害的样子

**Comment by popomore** [comment]
webpack 有server 方案么？看来我以后要取 webpack 社区混了。

**Comment by wanderBee** [comment]
+1

**Comment by sorrycc** [comment]
@popomore spm-server 兼容以上功能的。webpack 也有一个，还没仔细看。

**Comment by alvin2ye** [comment]
+1

**Comment by majorye** [comment]
不错～
