### ISSUE TITLE
支持css模块语法

### ISSUE THREAD

**Issue by shepherdwind** [spmjs/spm-webpack#24]
css-loader是支持 `:local` [语法](https://github.com/webpack/css-loader#local-scope)的，这个在css模块化上非常有用。

spm-webpack需要升级两个包
1.  extract-text-webpack-plugin 到 ~0.8.2
2.  css-loader 到 0.15.6

**Comment by soda-x** [comment]
好 .  在最近一个版本中我同步更新下

**Comment by soda-x** [comment]
https://github.com/spmjs/spm-webpack/pull/28

**Comment by soda-x** [comment]
因为发现 新版  `extract-text-webpack-plugin` 对 css 顺序要求严格，从原先的 0.7.5 的小版本 变为 0.8.0 支持.
