### ISSUE TITLE
jsx使用babel-loader

### ISSUE THREAD

**Issue by shepherdwind** [spmjs/spm-webpack#32]
现在还是jsx2-loader，另外，能不能出一个简单一些版本，spm-webpack应该不需要监听本地文件修改的。

另外gnode也可以去掉了吧。spm老大了

**Comment by soda-x** [comment]
确实很大 - -！ 

会修复的

**Comment by hotoo** [comment]
#38

**Comment by soda-x** [comment]
已经merge
