### ISSUE TITLE
bug: less 不能 @import 相对路径的 css 文件

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm-webpack#4]
原因：
- `@import (css) './a.css'` 会被编译成 `@import 'a.css'`，而不是 `@import './a.css'`
- `a.css` 在 spm 中是作为依赖包解析的，不会对应到本地文件

**Comment by popomore** [comment]
这个是 less 的问题吧？

**Comment by sorrycc** [comment]
@popomore 主贴补充了下说明。

**Comment by popomore** [comment]
恩，不过感觉用 less 还要用 spm 的？

**Comment by army8735** [comment]
做成插件形式吧

**Comment by popomore** [comment]
https://www.npmjs.org/package/css-imports

改这个吧

**Comment by popomore** [comment]
发一个 1.0 版本

**Comment by popomore** [comment]
感觉 spm 要发 4.0 啊

**Comment by popomore** [comment]
不过我觉得 webpack 这种写法也很 hack，和 js 保持一致反而好理解。

**Comment by sorrycc** [comment]
webpack 很 '智能' 地多做了些事情。

比如下面的情况：

```
- a.less
+ foo
  - b.less
```

然后
- a.less import ./foo/b.less
- b.less import c

最终：

webpack 会把 b.less 处理成 import foo/c

---

今天一路踩了不少 css 的坑，感觉既然用了 webpack 就跟着他的那一套规范走吧，可以少很多事。

**Comment by sorrycc** [comment]
第一眼也感觉有点怪，后面看看其实还好。。主要是 less 等预编译库也是基于这套规则 (https://github.com/spmjs/spm-sea/issues/2) 来的。

**Comment by popomore** [comment]
哪个文档有关于 css 和预编译引用的介绍么

**Comment by sorrycc** [comment]
编译一个看看就知道了啊。`@import (css) './a.css'` 会被编译成 `@import 'a.css'`

**Comment by popomore** [comment]
看下所有的规则，css 里也是 `@import 'a.css'` 么？

less 里也可以直接写成 `@import (css) 'a.css'`？

**Comment by afc163** [comment]
`@import (css) url('./a.css')` 呢

**Comment by sorrycc** [comment]
@afc163 一样的，也是 `@import url('a.css');`。

**Comment by army8735** [comment]
都会去掉./的，浏览器实现如此

**Comment by sorrycc** [comment]
按 webpack 的规则走，已无此问题。(https://github.com/spmjs/spm-sea/issues/2)
