### ISSUE TITLE
重复打包的问题

### ISSUE THREAD

**Issue by jaredleechn** [spmjs/spm-webpack#46]
`spm-webpack@1.0.0` 现在如果在 npm2 目录结构下直接打包如图依赖关系，并且 `d 没有被 a 直接依赖`，会出现 `d` 重复打包问题：

```
a
|--b
    |--d
|--c
    |--d
```

重现：`rc-select`、`rc-tabs`，发现 `rc-animate` 被重复打包，如果增加 `rc-animate` 直接被项目依赖，无重复打包问题

@sorrycc @pigcan

**Comment by soda-x** [comment]
确实有这个问题， 这个问题确定升级 `npm` or `tnpm` 到 3能解决的话就推荐升级吧.  让构建平台也去升级下. 

估计不好解决 spm 逻辑中这本来就应该打2份 .

**Comment by jaredleechn** [comment]
解决方案：升级 npm3或将该模块直接被项目依赖

**Comment by sorrycc** [comment]
http://webpack.github.io/docs/list-of-plugins.html#dedupeplugin
可以加 dedupe 插件，不过 spm-webpack 建议就不优化了
