### ISSUE TITLE
spm build偶现报错

### ISSUE THREAD

**Issue by stonelee** [spmjs/spm-webpack#49]
我们在使用spm构建的时候发现了个问题，在copy文件的时候报错，如下：

![](https://zos.alipayobjects.com/rmsportal/FarTWSPklRqngvuFqJoh.png)

看了下spm-webpack的代码，看起来是这里的问题：

![](https://zos.alipayobjects.com/rmsportal/zZpVtnoWWvTZpFTFmTfx.png)

是否应该是`fs.mkdirSync`，或者下面那个mkdirp应该用sync的方法？

**Comment by soda-x** [comment]
确实有可能会偶现这个问题，应该是 mkdirSync 的问题

目前 spmjs 的内容已经停止维护了，如果要解决当下问题可以在调用构建命令时先保证目录已经生成。
