### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm-webpack#5]
**问题**

webpack 产出文件的路径是拍平的，不能保留路径。比如：entry 是 `src/a.js`，output 只能是 `dist/a.js`，不能是 `dist/src/a.js`。

https://github.com/webpack/webpack/issues/902

**尝试**

试过可以通过一些方法保持原路径 (name 带路径)，但是遇到坑：css 引用的图片字体文件的路径会不对

**解决**

跟着 webpack 走，拍平目录

**新问题**

项目如果包含 html，拍平复制过去之后，引用 css, js 等资源的路径会不对。

**解决**

处理 html 里的引用资源，把引用路径也拍平。

**Comment by afc163** [comment]
standalone 的方式，拍平比较合适。

**Comment by limichange** [comment]
有没有插件可以解决这个问题？

**Comment by sorrycc** [comment]
最终还是保留路径了，拍平不满足一些复杂的项目场景，并且处理起路径来感觉坑更多。现在是通过一个插件来修复 `css 引用的图片字体文件的路径会不对` 的问题。

https://github.com/spmjs/spm-webpack/blob/0adfde6ee3bf8eb2aa39412fab4a98a952f970f3/lib/FixCSSPathPlugin.js

**Comment by xyyjk** [comment]
@sorrycc @afc163 @limichange 
`css 引用的图片字体文件的路径会不对` 这个问也困扰了我一段时间，后来从 `file-loader` 的测试用例中找到了答案：https://github.com/webpack/file-loader/blob/master/test/correct-filename.test.js#L46

可参照如下代码：

```
{
  test  : /\.(png|gif|jpe?g|svg|eot|ttf|woff|woff2)$/,
  loader: 'url?limit=8192&name=[path][name].[ext]?[hash:8]&context=src'
}
```

重点是 `[path]` 及 `context=src`，`src` 为开发目录。

**Comment by sharkrice** [comment]
context参数有什么用啊？
官方文档也没有说。
