### ISSUE TITLE
参数整理

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm-webpack#6]
整理了配置项，构建相关的参数放到 build 下了。(https://github.com/spmjs/spm-argv/issues/1)

@popomore @afc163 看下有没有问题。比如命名或者其他的问题。

``` javascript
{
  "name": "",
  "version": "",

  "spm": {

    "build": {
      // -- 依赖解析
      // 指定不解析的模块或文件
      "global": {
        "react": "React",
        "./a": "AAA"
      },
      // 开启或禁用 node 模块的 polyfills
      "node": {
        "global": false
      },

      // -- 性能
      // 提取依赖为 vendor.js
      "vendor": ["jquery", "underscore"],
      // 提取公共 chunk 为 common.js
      "common": true,
      "base64": {},

      // -- 语言类
      "babel": {},
      "uglify": {},
      "autoprefixer": {},
      "less": {},
      "coffee": {},
      "jsx": {},
      "handlebars": {},

      // -- 输出
      "dest": "./build",
      "hash": true,
      // 提取入口 js 文件依赖链中的 CSS chunk，输出和入口文件同名的 css 文件
      "extractCSS": true,
      // 输出的包名
      "library": "",
      // this, umd, common, amd, var 等等
      "libraryTarget": "",
      // 等同于 libraryTarget: umd, library: Foo
      "umd": "Foo",

      // -- 扩展
      "loader": {
        ".js": "+jsdc-babel"
      }
    },

    "registry": ""
  }
}
```

**Comment by sorrycc** [comment]
命令行参数：
- `--force`, 从源上重新拉依赖包
- `--clean`, 清空 output directory
- `--watch`, watch mode
- `--registry`
- `--debug`, 不压缩
- `--verbose`, 更多日志

**Comment by afc163** [comment]
很复杂和强大，可以说明下哪些配置和 webpack 是一致的。

**Comment by sorrycc** [comment]
明天我搞个对照表。

**Comment by sorrycc** [comment]
对照表：

| spm | webpack | note |
| --- | --- | --- |
| global | externals |  |
| node | node |  |
| vendor | CommonsChunkPlugin |  |
| common | CommonsChunkPlugin |  |
| base64 | url-loader |  |
| babel | babel-loader |  |
| uglify | UglifyJsPlugin |  |
| autoprefixer | autoprefixer-loader |  |
| less | less-loader |  |
| coffee | coffee-loader |  |
| jsx | jsx2-loader |  |
| handlebars | handlebars-loader |  |
| library | library |  |
| libraryTarget | libraryTarget |  |
| umd |  |  |
| extractCSS | ExtractTextPlugin |  |
| hash | [hash] in filename |  |
| loader |  |  |

参考：
http://webpack.github.io/docs/configuration.html
http://webpack.github.io/docs/list-of-plugins.html
http://webpack.github.io/docs/list-of-loaders.html

**Comment by sorrycc** [comment]
https://github.com/spmjs/docs/blob/master/project/configuration.md
整理到文档了。
